SU(:) = 0.0; SV(:) = 0.0; SW(:) = 0.0;

% The momentum sources/sinks are updated here
[SU,SV,SW] = UpdateMomSource(SourceMaskFunction1,SU,SV,SW,U,V,W,Umax,Vmax,-Wmax,dt);
[SU,SV,SW] = UpdateMomSource(SourceMaskFunction2,SU,SV,SW,U,V,W,Umax,Vmax,-Wmax,dt);
[SU,SV,SW] = UpdateMomSource(SourceMaskFunction3,SU,SV,SW,U,V,W,Umax,Vmax,Wmax,dt);
[SU,SV,SW] = UpdateMomSource(SourceMaskFunction4,SU,SV,SW,U,V,W,Umax,Vmax,Wmax,dt);
     
dU = (-(0.5.*(U(iny,east,inz)+U(iny,inx,inz)).*0.5.*(U(iny,east,inz)+U(iny,inx,inz))/dx - ...
     0.5.*(U(iny,inx,inz)+U(iny,west,inz)).*0.5.*(U(iny,inx,inz)+U(iny,west,inz))/dx + ...
     0.5.*(V(north,inx,inz)+V(iny,inx,inz)).*0.5.*(U(north,inx,inz)+U(iny,inx,inz))/dy - ...
     0.5.*(V(iny,inx,inz)+V(south,inx,inz)).*0.5.*(U(iny,inx,inz)+U(south,inx,inz))/dy + ...
     0.5.*(W(iny,inx,front)+W(iny,inx,inz)).*0.5.*(U(iny,inx,front)+U(iny,inx,inz))/dz - ...
     0.5.*(W(iny,inx,inz)+W(iny,inx,back)).*0.5.*(U(iny,inx,inz)+U(iny,inx,back))/dz) + ...
     nu*((U(iny,east,inz) - 2.0*U(iny,inx,inz) + U(iny,west,inz))/(dx*dx) + ...
     (U(north,inx,inz) - 2.0*U(iny,inx,inz) + U(south,inx,inz))/(dy*dy) + ...
     (U(iny,inx,front) - 2.0*U(iny,inx,inz) + U(iny,inx,back))/(dz*dz)) + SU)*dt;
     
dV = (-(0.5.*(U(iny,east,inz)+U(iny,inx,inz)).*0.5.*(V(iny,east,inz)+V(iny,inx,inz))/dx - ...
     0.5.*(U(iny,inx,inz)+U(iny,west,inz)).*0.5.*(V(iny,inx,inz)+V(iny,west,inz))/dx + ...
     0.5.*(V(north,inx,inz)+V(iny,inx,inz)).*0.5.*(V(north,inx,inz)+V(iny,inx,inz))/dy - ...
     0.5.*(V(iny,inx,inz)+V(south,inx,inz)).*0.5.*(V(iny,inx,inz)+V(south,inx,inz))/dy + ...
     0.5.*(W(iny,inx,front)+W(iny,inx,inz)).*0.5.*(V(iny,inx,front)+V(iny,inx,inz))/dz - ...
     0.5.*(W(iny,inx,inz)+W(iny,inx,back)).*0.5.*(V(iny,inx,inz)+V(iny,inx,back))/dz) + ...
     nu*((V(iny,east,inz) - 2.0*V(iny,inx,inz) + V(iny,west,inz))/(dx*dx) + ...
     (V(north,inx,inz) - 2.0*V(iny,inx,inz) + V(south,inx,inz))/(dy*dy) + ...
     (V(iny,inx,front) - 2.0*V(iny,inx,inz) + V(iny,inx,back))/(dz*dz)) + SV)*dt;
     
dW = (-(0.5.*(U(iny,east,inz)+U(iny,inx,inz)).*0.5.*(W(iny,east,inz)+W(iny,inx,inz))/dx - ...
     0.5.*(U(iny,inx,inz)+U(iny,west,inz)).*0.5.*(W(iny,inx,inz)+W(iny,west,inz))/dx + ...
     0.5.*(V(north,inx,inz)+V(iny,inx,inz)).*0.5.*(W(north,inx,inz)+W(iny,inx,inz))/dy - ...
     0.5.*(V(iny,inx,inz)+V(south,inx,inz)).*0.5.*(W(iny,inx,inz)+W(south,inx,inz))/dy + ...
     0.5.*(W(iny,inx,front)+W(iny,inx,inz)).*0.5.*(W(iny,inx,front)+W(iny,inx,inz))/dz - ...
     0.5.*(W(iny,inx,inz)+W(iny,inx,back)).*0.5.*(W(iny,inx,inz)+W(iny,inx,back))/dz) + ...
     nu*((W(iny,east,inz) - 2.0*W(iny,inx,inz) + W(iny,west,inz))/(dx*dx) + ...
     (W(north,inx,inz) - 2.0*W(iny,inx,inz) + W(south,inx,inz))/(dy*dy) + ...
     (W(iny,inx,front) - 2.0*W(iny,inx,inz) + W(iny,inx,back))/(dz*dz)) + SW)*dt;
