% This script outputs the fluid fields in a VTK file

vtkwrite('RoomEmptyingExtraWallLargeDNSLABIBUMean.vtk', ...
'structured_grid',X,Y,Z,'scalars','UMean',UMean,'scalars', ...
'VMean',VMean,'scalars','WMean',WMean, ...
'U',U,'scalars','V',V,'scalars','W',W, ...
'scalars','Beta',Beta,'binary');
